import type { Metadata } from "next";
import "./styles/globals.css";
import {Montserrat, Roboto, Pacifico } from "next/font/google";
import AOSInit from "./_components/AOS";
import Providers from "./provider";
import Script from "next/script";

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  variable: "--font-spicy-rice",
});

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
export const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cursive",
});

export const metadata: Metadata = {
  title: "Dry Basket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${roboto.variable} ${pacifico.variable} antialiased`}
      >
        <AOSInit />
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="beforeInteractive"/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
